### ISSUE TITLE
Request: Support CoffeeKup/Coffeecup Syntax

### ISSUE THREAD

**Issue by m1sta** [jsdf/coffee-react#12]
How difficult would it be to support https://github.com/gradus/coffeecup?

**Comment by jbe** [comment]
@jsdf In case you're still wondering, the project he's linking to is a template syntax that is itself just coffeescript. When using CoffeeCup there would be no need to mix html and CoffeeScript as in *jsx, because now both template and component logic can be written in CoffeeScript, in the same file. Just have a look at the example in the page, it's worth it! Not that i'm expecting anyone to do the hard work of implementing it just because some says they like it on github.
